title: Michael Ruocco - CV
url: "https://michaelruocco.github.io"
baseurl: '/online-cv'

description: Michael Ruocco - CV
theme_skin: ceramic
chrome_mobile_color:

analytics:

sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

port: 4000
host: 0.0.0.0
safe: false
